#!/usr/bin/env bash
# Generate 3 ML-DSA-65 validator keypairs for mainnet and write Ansible vars.
#
# Usage: VIPER_PASSPHRASE=<secret> scripts/gen_mainnet_keys.sh
#   Output: deploy/ansible/group_vars/mainnet_keys.yml  (gitignored — contains seeds)
#
# The passphrase encrypts the keystore files only. The seeds are also written
# to mainnet_keys.yml so Ansible can seed the validator config. Store that file
# in a secrets manager (Vault, SOPS) and never commit it to git.

set -euo pipefail
cd "$(dirname "$0")/.."

BINARY="./target/release/pqcd"
if [[ ! -x "$BINARY" ]]; then
  echo "ERROR: $BINARY not found — run: cargo build --release" >&2
  exit 1
fi

if [[ -z "${VIPER_PASSPHRASE:-}" ]]; then
  echo "ERROR: set VIPER_PASSPHRASE before running this script" >&2
  exit 1
fi

KEYSTORE_DIR="$HOME/.viper/keystore"
mkdir -p "$KEYSTORE_DIR"

echo "Generating 3 ML-DSA-65 validator keypairs..."

V1=$(VIPER_PASSPHRASE="$VIPER_PASSPHRASE" "$BINARY" keygen \
  --passphrase "$VIPER_PASSPHRASE" \
  --output "$KEYSTORE_DIR/validator-1.json")

V2=$(VIPER_PASSPHRASE="$VIPER_PASSPHRASE" "$BINARY" keygen \
  --passphrase "$VIPER_PASSPHRASE" \
  --output "$KEYSTORE_DIR/validator-2.json")

V3=$(VIPER_PASSPHRASE="$VIPER_PASSPHRASE" "$BINARY" keygen \
  --passphrase "$VIPER_PASSPHRASE" \
  --output "$KEYSTORE_DIR/validator-3.json")

parse() { echo "$1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['$2'])"; }

OUT="deploy/ansible/group_vars/mainnet_keys.yml"
cat > "$OUT" <<YAML
---
# GENERATED by scripts/gen_mainnet_keys.sh — DO NOT COMMIT
# Store in Vault / SOPS. Seeds are SECRET.

viper_chain_id: "viper-mainnet-1"
viper_anchor_prev_hash_hex: "0000000000000000000000000000000000000000000000000000000000000000"

viper_validators:
  - node_id: "validator-1"
    address_hex: "$(parse "$V1" address_hex)"
    sig_alg_id: 2
    commit_seed_hex: "$(parse "$V1" seed_hex)"
    public_key_hex: "$(parse "$V1" public_key_hex)"

  - node_id: "validator-2"
    address_hex: "$(parse "$V2" address_hex)"
    sig_alg_id: 2
    commit_seed_hex: "$(parse "$V2" seed_hex)"
    public_key_hex: "$(parse "$V2" public_key_hex)"

  - node_id: "validator-3"
    address_hex: "$(parse "$V3" address_hex)"
    sig_alg_id: 2
    commit_seed_hex: "$(parse "$V3" seed_hex)"
    public_key_hex: "$(parse "$V3" public_key_hex)"

viper_genesis_accounts:
  - address_hex: "$(parse "$V1" address_hex)"
    balance: 1000000000000000000000000000
    nonce: 0
    keys:
      - alg_id: 2
        key_version: 1
        valid_from_height: 0
        status: "active"
        allowed_tx_types: 15
        pk_hex: "$(parse "$V1" public_key_hex)"

viper_proposer_address_hex: "$(parse "$V1" address_hex)"
YAML

chmod 600 "$OUT"

echo ""
echo "Keys written to: $OUT"
echo "Keystores saved in: $KEYSTORE_DIR"
echo ""
echo "validator-1 address: $(parse "$V1" address_hex)"
echo "validator-2 address: $(parse "$V2" address_hex)"
echo "validator-3 address: $(parse "$V3" address_hex)"
echo ""
echo "Next: ansible-playbook -i deploy/ansible/inventory/hosts.yml deploy/ansible/playbooks/site.yml"
