{{/*
ADR-069 §4 — refuse to render values that were generated by `pqcd ceremony`
for another release name or namespace. The per-role node.json embeds the
validator / sentry headless-service multiaddrs, which carry both; a mismatch
leaves every follower dialling a name that does not exist (the viper-lab-1
cold-start failure of 2026-08).
*/}}
{{- define "viper-pq-chain.guardCeremonyValues" -}}
{{- $want := .Values._release_name | default "" -}}
{{- if and $want (ne $want .Release.Name) -}}
{{- fail (printf "values were generated by `pqcd ceremony` for release %q but this release is %q — re-run the ceremony with --release-name %s or install with that name" $want .Release.Name .Release.Name) -}}
{{- end -}}
{{- $ns := .Values._namespace | default "" -}}
{{- if and $ns (ne $ns .Release.Namespace) -}}
{{- fail (printf "values were generated by `pqcd ceremony` for namespace %q but this install targets %q" $ns .Release.Namespace) -}}
{{- end -}}
{{- end -}}
